<a href="https://colab.research.google.com/github/narendra974/NLPBasics/blob/main/NextCharMLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
!git clone https://github.com/narendra974/NLPBasics.git

Cloning into 'NLPBasics'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 26 (delta 6), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (26/26), 504.28 KiB | 4.76 MiB/s, done.
Resolving deltas: 100% (6/6), done.


In [3]:
words = open('NLPBasics/data/names.txt', 'r').read().splitlines()

In [4]:
words[0:8]

['emma', 'olivia', 'ava', 'isabella', 'sophia', 'charlotte', 'mia', 'amelia']

In [5]:
len(words)

32033

In [6]:
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i, s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s, i  in stoi.items()}

In [9]:
block_size = 3
X, Y = [], []

for w in words[0:5]:
  context = [0]*block_size
  for ch in w + '.':
    ix = stoi[ch]
    X.append(context)
    Y.append(ix)
    print(''.join(itos[i] for i in context), '--->', itos[ix])
    context = context[1:] + [ix]

X = torch.tensor(X)
Y = torch.tensor(Y)

... ---> e
..e ---> m
.em ---> m
emm ---> a
mma ---> .
... ---> o
..o ---> l
.ol ---> i
oli ---> v
liv ---> i
ivi ---> a
via ---> .
... ---> a
..a ---> v
.av ---> a
ava ---> .
... ---> i
..i ---> s
.is ---> a
isa ---> b
sab ---> e
abe ---> l
bel ---> l
ell ---> a
lla ---> .
... ---> s
..s ---> o
.so ---> p
sop ---> h
oph ---> i
phi ---> a
hia ---> .


In [10]:
X.shape, X.dtype, Y.shape, Y.dtype

(torch.Size([32, 3]), torch.int64, torch.Size([32]), torch.int64)

In [11]:
C = torch.randn((27, 2))
C

tensor([[ 1.9281, -0.1665],
        [ 0.5924,  1.2323],
        [-0.4177, -1.9438],
        [ 1.8064,  1.2362],
        [ 0.5034, -1.4818],
        [ 0.8340,  0.7454],
        [ 0.2307, -1.1560],
        [-1.4295,  0.6157],
        [-0.3203,  0.6798],
        [-0.1737,  0.4162],
        [-0.2779,  1.1383],
        [-0.6898, -1.6434],
        [ 0.0455, -0.2791],
        [ 1.2057,  1.4643],
        [ 0.4907, -0.0437],
        [ 0.0650,  0.7828],
        [-1.4897, -0.7957],
        [ 1.3549, -0.5730],
        [-0.8822,  1.2965],
        [-1.1502,  0.4337],
        [-1.7924,  0.5420],
        [-2.3641,  0.5079],
        [-0.8373, -0.6023],
        [-0.2418,  1.1374],
        [ 0.5933, -1.5033],
        [ 0.1536,  0.3377],
        [-0.5614,  0.3216]])

In [13]:
C[5]

tensor([0.8340, 0.7454])

In [12]:
F.one_hot(torch.tensor(5), num_classes=27).float() @ C

tensor([0.8340, 0.7454])